#!/bin/bash
########################################################################################################################
## Simple script to convert all of the svg files in this directory to png files in ../png
########################################################################################################################

cd $(dirname $0)

mkdir -p ../png

for x in *.svg; do
  OUTPUT=../png/$(echo $x | sed 's/svg$/png/')
  for size in 32 64 128 256; do
    OUTPUT_SIZED=$(echo $OUTPUT | sed "s/\.png$/-${size}x${size}.png/")
    echo "Converting $x to $OUTPUT_SIZED"
    rsvg-convert -o $OUTPUT_SIZED -w ${size} -h ${size} $x
  done
done
