#!/bin/bash
########################################################################################################################
## Simple script to convert all of the svg files in this directory to png files in ../png
########################################################################################################################

cd $(dirname $0)

mkdir -p ../png

for x in *.svg; do
  OUTPUT=../png/$(echo $x | sed 's/svg$/png/')
  echo "Converting $x to $OUTPUT"
  rsvg-convert -o $OUTPUT $x
done
